### ISSUE TITLE
ISSUE: No client header provided

### ISSUE THREAD

**Issue by vzool** [paragonie/chronicle#24]
Hi,

I did setup a two Chronicle instances which are `Chronicle-A` and `Chronicle-B`. I generated keypairs with `php bin/keygin.php` at `Chronicle-A`, then I took public key and create a new client with `php bin/create-client.php` at `Chronicle-B` which gave me a **success result**.

```
➜  php bin/create-client.php --publickey="N1DIRAN2XpXaIJpFx2IpDQpqF4j0bkGDhkmlNBI_NHU=" --comment="point-BB"
	Client (VeVGBO9gThq_eTzCbAR3vgrhEHrUnRqL) created successfully!
```

I try to test publish some data with the following code:

```php
<?php

$root = \dirname(__DIR__);
/** @psalm-suppress UnresolvableInclude */
require_once $root . '/cli-autoload.php';

use GuzzleHttp\Client;
use ParagonIE\Sapient\Sapient;
use ParagonIE\ConstantTime\Base64UrlSafe;
use ParagonIE\Sapient\Adapter\Guzzle as GuzzleAdapter;
use ParagonIE\Sapient\CryptographyKeys\SigningPublicKey;
use ParagonIE\Sapient\CryptographyKeys\SigningSecretKey;
use ParagonIE\Sapient\Exception\InvalidMessageException;

$http = new Client([
    'base_uri' => 'http://localhost:8080'
]);
$sapient = new Sapient(new GuzzleAdapter($http));

// Keys
$clientSigningKey = new SigningSecretKey(
    Base64UrlSafe::decode(
        'JblJ6oEbqA8pBQKbwX_gSb7wCP85--C9ANyRU-eYGUM3UMhEA3ZeldogmkXHYikNCmoXiPRuQYOGSaU0Ej80dQ=='
    )
);
$serverPublicKey = new SigningPublicKey(
    Base64UrlSafe::decode(
        'N1DIRAN2XpXaIJpFx2IpDQpqF4j0bkGDhkmlNBI_NHU='
    )
);

// We use an array to define our message
$myMessage = [
    'date' => (new DateTime)->format(DateTime::ATOM),
    'body' => [
        'test' => 'hello world!'        
    ]
];

// Create the signed request:
$request = $sapient->createSignedJsonRequest(
    'POST',
     '/chronicle/publish',
     $myMessage,
     $clientSigningKey
);

$response = $http->send($request);
try {
    /** @var array $verifiedResponse */
    $verifiedResponse = $sapient->decodeSignedJsonResponse(
        $response,
        $serverPublicKey
    );
} catch (InvalidMessageException $ex) {
    echo $ex->getMessage();
    // \http_response_code(500);
    exit;
}
```

Then, I received this error:

```
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST http://localhost:8080/chronicle/publish` resulted in a `403 Forbidden` response:
{
    "version": "1.0.x",
    "datetime": "2018-07-06T19:57:36+00:00",
    "status": "ERROR",
    "message": "No client  (truncated...)
in /Users/vzool/Workspace/chronicleA/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /Users/vzool/Workspace/chronicleA/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /Users/vzool/Workspace/chronicleA/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /Users/vzool/Workspace/chronicleA/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /Users/vzool/Workspace/chronicleA/vendor/guzzlehttp/promises/src/TaskQueue.php(47): Guzzl in /Users/vzool/Workspace/chronicleA/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

```

After I dig more into `Publish Handler` I found the truncated message, which is here:

```
No client header provided 
```
 
What I did miss here?

Thanks

**Comment by paragonie-scott** [comment]
> What I did miss here?

See `Client (VeVGBO9gThq_eTzCbAR3vgrhEHrUnRqL) created successfully!`.

That's your Client ID. It needs to be sent in an HTTP header alongside the request.

Try this change:

```diff
$request = $sapient->createSignedJsonRequest(
    'POST',
     '/chronicle/publish',
     $myMessage,
     $clientSigningKey
+    [
+        Chronicle::CLIENT_IDENTIFIER_HEADER =>
+            'VeVGBO9gThq_eTzCbAR3vgrhEHrUnRqL'
+    ]
);
```

**Comment by vzool** [comment]
Great, it works fine now.

But, I noticed that there is no any `Foreign Keys`!
I thought there should be many constraints like a foreign key between  `prevhash -> currhash`:

```sql
ALTER TABLE chronicle_chain
ADD CONSTRAINT chronicle_chain_prevhash_currhash_fk
FOREIGN KEY (prevhash)
REFERENCES chronicle_chain(currhash)
ON DELETE RESTRICT;
```

Why there is no any `Foreign Keys`? ^_^

Thanks

**Comment by vzool** [comment]
BTW, I already tried and it fails. Ha ha ha
I think it does need a `Genesis Block` in order to start dancing with `RDBMS` relationships. :)

**Comment by vzool** [comment]
I will close this and open another one for `Genesis Block`.
