### ISSUE TITLE
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value

### ISSUE THREAD

**Issue by vzool** [paragonie/chronicle#32]
I started testing out now after fixing database creation for **MySQL**. So, error show up when publish data:

```bash
Type: PDOException
Code: 22007
Message: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2018-10-19T21:18:39+00:00' for column 'created' at row 1
File: /home/vagrant/code/my-chronicle/vendor/paragonie/easydb/src/EasyDB.php
Line: 846
Trace: #0 /home/vagrant/code/my-chronicle/vendor/paragonie/easydb/src/EasyDB.php(846): PDOStatement->execute(Array)
#1 /home/vagrant/code/my-chronicle/vendor/paragonie/easydb/src/EasyDB.php(521): ParagonIE\EasyDB\EasyDB->safeQuery('INSERT INTO `ch...', Array, 4, true)
#2 /home/vagrant/code/my-chronicle/src/Chronicle/Chronicle.php(114): ParagonIE\EasyDB\EasyDB->insert('chronicle_chain', Array)
#3 /home/vagrant/code/my-chronicle/src/Chronicle/Handlers/Publish.php(92): ParagonIE\Chronicle\Chronicle::extendBlakechain('{\n    "date": "...', 'w8J2tTFL5THh4P_...', Object(ParagonIE\Sapient\CryptographyKeys\SigningPublicKey))
#4 [internal function]: ParagonIE\Chronicle\Handlers\Publish->__invoke(Object(Slim\Http\Request), Ob" while reading response header from upstream, client: 192.168.10.1, server: chronicle.local, request: "POST /chronicle/publish HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "chronicle.local"
```
More investigation will going on tomorrow morning, if God's will. ^_^

**Comment by vzool** [comment]
I couldn't sleep 🙂
So, I did the investigation and the `datetime` in this format `'2018-10-19T21:18:39+00:00'` is invalid for **MySQL**. I normally use this way when handling  `datetime` in MySQL by myself:

```php
$datetime = date('Y-m-d H:i:s'); // 2018-10-19 21:18:39
```
I'm not sure if this will work for PostgreSQL & SQLite. 😕
I'm thinking that we just need to make this created/updated things at a database level? 🤔
