### ISSUE TITLE
PostgreSQL Invalid foreign key: there is no unique constraint matching given keys for referenced table "chronicle_replication_chain"

### ISSUE THREAD

**Issue by vzool** [paragonie/chronicle#52]
Hi, there is an issue when building database for **PostgreSQL v9.6.7**.

Here is the output:

```sh
$ php bin/make-tables.php
/var/www/public/workspace/chronicle/sql/pgsql/00-local.sql
/var/www/public/workspace/chronicle/sql/pgsql/01-remote.sql
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42830]: Invalid foreign key: 7 ERROR:  there is no unique constraint matching given keys for referenced table "chronicle_replication_chain" in /var/www/public/workspace/chronicle/vendor/paragonie/easydb/src/EasyDB.php:1329
Stack trace:
#0 /var/www/public/workspace/chronicle/vendor/paragonie/easydb/src/EasyDB.php(1329): PDO->query('CREATE TABLE ch...')
#1 /var/www/public/workspace/chronicle/bin/make-tables.php(125): ParagonIE\EasyDB\EasyDB->query('CREATE TABLE ch...')
#2 {main}
  thrown in /var/www/public/workspace/chronicle/vendor/paragonie/easydb/src/EasyDB.php on line 1329
```

Thanks

**Comment by paragonie-scott** [comment]
I *believe* this is fixed in https://github.com/paragonie/chronicle/commit/65554de8b0d1b931e625008972087c05239295bb. Please let me know if you still encounter this problem after updating.
